trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  displayName: Azure CLI test
  inputs:
    azureSubscription: AzurePipelines_SP
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az account show
