trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  armServiceConnection: 'AzurePipelines_SP'
  ResourceGroup: 'oda_sandbox'
  YAMLName: 'deploy-aci.yml'

steps:
- task: AzureCLI@2
  displayName: ACI Deploy
  inputs:
    azureSubscription: $(armServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      # az container create -g $(ResourceGroup) --file $(YAMLName)
